development:
  secret_key_base: 10d937514c8f24f127286368180e1e2c203d5482e68d53d789f4dde4cb872137385b14d88de74414dcfe2e0e04621d14c72592e4f81a74328390d7b98f74
test:
  secret_key_base: d9bf7d044da022736fe4a073ff26a696926bb31393730731d2f1e7774e1cf98589b4855412d02d3303ba5522632627a6b5601a37031eb3be483344446f8ec47
production:
  secret_key_base: 10d937514c8f24f127286368180e1e2c203d5482e68d53d789f4dde4cb872137385b14d88de74414dcfe2e0e04621d14c72592e4f81a74328390d7b98f741bad45
